<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Printing\PrintInput\新しいフォルダー\**" />
    <Compile Remove="Printing\新しいフォルダー1\**" />
    <EmbeddedResource Remove="Printing\PrintInput\新しいフォルダー\**" />
    <EmbeddedResource Remove="Printing\新しいフォルダー1\**" />
    <None Remove="Printing\PrintInput\新しいフォルダー\**" />
    <None Remove="Printing\新しいフォルダー1\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Printing\PrintDiagram\KAJYU_ZU23.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="fonts\MS Gothic.ttf" />
    <None Remove="fonts\MS Mincho.ttf" />
    <None Remove="fonts\simsun.ttf" />
    <None Remove="Printing\PrintDiagram\InputDiagramFsec.cs~RF5f8c188b.TMP" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="fonts\MS Gothic.ttf" />
    <EmbeddedResource Include="fonts\MS Mincho.ttf" />
    <EmbeddedResource Include="fonts\simsun.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="PdfSharpCore" Version="1.3.9" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.13" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>PDF_Manager.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
